--- #YAML:1.0
name: Gestinanna
version: 0.02
license: perl
distribution_type: module
requires:
  Alzabo: 0.82
  Archive::Tar: 0
  Data::UUID: 0
  Email::Valid: 0
  Error: 0.15
  Gestinanna::POF: 0.06
  Gestinanna::POF::Repository: 0.03
  Lingua::EN::Inflect: 1.88
  Lingua::Preferred: 0.2
  Mail::Sendmail: 0
  Module::Require: 0.05
  Template: ~
  Workflow: 0.03
  XML::LibXML: ~
recommends:
  DBD::SQLite: 0
  Expect: 0
  IO::Pty: 0
  Term::Size: 0.2
build_requires: {}
conflicts: {}
provides:
  Apache::Template::Provider::Gestinanna:
    file: lib/Apache/Template/Provider/Gestinanna.pm
  Gestinanna:
    file: lib/Gestinanna.pm
    version: 0.02
  Gestinanna::Authz:
    file: lib/Gestinanna/Authz.pm
    version: 0.00_02
  Gestinanna::ContentProvider:
    file: lib/Gestinanna/ContentProvider.pm
  Gestinanna::ContentProvider::Document:
    file: lib/Gestinanna/ContentProvider/Document.pm
  Gestinanna::ContentProvider::Portal:
    file: lib/Gestinanna/ContentProvider/Portal.pm
  Gestinanna::ContentProvider::TT2:
    file: lib/Gestinanna/ContentProvider/TT2.pm
    version: 1.01
  Gestinanna::ContentProvider::TT2::TemplateProvider:
    file: lib/Gestinanna/ContentProvider/TT2.pm
    version: 1.01
  Gestinanna::ContentProvider::XSM:
    file: lib/Gestinanna/ContentProvider/XSM.pm
  Gestinanna::Exception:
    file: lib/Gestinanna/Exception.pm
  Gestinanna::POF::Secure::Gestinanna:
    file: lib/Gestinanna/POF/Secure/Gestinanna.pm
    version: 0.01
  ? |-
    Gestinanna::POF::Secure::Gestinanna::RepositoryObject
:
    file: |-
      lib/Gestinanna/POF/Secure/Gestinanna/RepositoryObject.pm
  Gestinanna::Request:
    file: lib/Gestinanna/Request.pm
  Gestinanna::SchemaManager:
    file: lib/Gestinanna/SchemaManager.pm
  Gestinanna::SchemaManager::Schema:
    file: lib/Gestinanna/SchemaManager/Schema.pm
  Gestinanna::Shell:
    file: lib/Gestinanna/Shell.pm
  Gestinanna::Shell::Base:
    file: lib/Gestinanna/Shell/Base.pm
  Gestinanna::Shell::Package:
    file: lib/Gestinanna/Shell/Package.pm
  Gestinanna::Shell::Schema:
    file: lib/Gestinanna/Shell/Schema.pm
  Gestinanna::Shell::Schema::Def:
    file: lib/Gestinanna/Shell/Schema/Def.pm
  Gestinanna::Shell::Site:
    file: lib/Gestinanna/Shell/Site.pm
  Gestinanna::Shell::Site::URI:
    file: lib/Gestinanna/Shell/Site.pm
  Gestinanna::SiteConfiguration:
    file: lib/Gestinanna/SiteConfiguration.pm
  Gestinanna::Upload:
    file: lib/Gestinanna/Upload.pm
  Gestinanna::Util:
    file: lib/Gestinanna/Util.pm
  Gestinanna::XSM:
    file: lib/Gestinanna/XSM.pm
  Gestinanna::XSM::Auth:
    file: lib/Gestinanna/XSM/Auth.pm
  Gestinanna::XSM::Authz:
    file: lib/Gestinanna/XSM/Authz.pm
  Gestinanna::XSM::Base:
    file: lib/Gestinanna/XSM/Base.pm
    version: 0.06
  Gestinanna::XSM::Base::CC:
    file: lib/Gestinanna/XSM/Base.pm
    version: 0.06
  Gestinanna::XSM::ContentProvider:
    file: lib/Gestinanna/XSM/ContentProvider.pm
  Gestinanna::XSM::DefaultHandler:
    file: lib/Gestinanna/XSM/DefaultHandler.pm
  Gestinanna::XSM::Diff:
    file: lib/Gestinanna/XSM/Diff.pm
  Gestinanna::XSM::Digest:
    file: lib/Gestinanna/XSM/Digest.pm
  Gestinanna::XSM::Expression:
    file: lib/Gestinanna/XSM/Expression.pm
  Gestinanna::XSM::Expression::Parser:
    file: lib/Gestinanna/XSM/Expression/Parser.pm
    version: 1.05
  Gestinanna::XSM::Gestinanna:
    file: lib/Gestinanna/XSM/Gestinanna.pm
  Gestinanna::XSM::LibXMLSupport:
    file: lib/Gestinanna/XSM/LibXMLSupport.pm
  Gestinanna::XSM::Op:
    file: lib/Gestinanna/XSM/DefaultHandler.pm
  Gestinanna::XSM::POF:
    file: lib/Gestinanna/XSM/POF.pm
  Gestinanna::XSM::SAXHandler:
    file: lib/Gestinanna/XSM.pm
  Gestinanna::XSM::SAXParser:
    file: lib/Gestinanna/XSM.pm
  Gestinanna::XSM::SMTP:
    file: lib/Gestinanna/XSM/SMTP.pm
  Gestinanna::XSM::SMTP::Message:
    file: lib/Gestinanna/XSM/SMTP.pm
  Gestinanna::XSM::Script:
    file: lib/Gestinanna/XSM/Script.pm
  Gestinanna::XSM::StateMachine:
    file: lib/Gestinanna/XSM/StateMachine.pm
  Gestinanna::XSM::Workflow:
    file: lib/Gestinanna/XSM/Workflow.pm
  Gestinanna::XSM::XMLSimple:
    file: lib/Gestinanna/XSM/XMLSimple.pm
  Parse::Yapp::Driver:
    file: lib/Gestinanna/XSM/Expression/Parser.pm
    version: 1.05
  StateMachine::Gestinanna::Exception:
    file: lib/Gestinanna/XSM/Base.pm
    version: 0.06
  activate:
    file: lib/Gestinanna/Shell/Package.pm
  create:
    file: lib/Gestinanna/Shell/Package.pm
  edit:
    file: lib/Gestinanna/Shell/Package.pm
  install:
    file: lib/Gestinanna/Shell/Package.pm
  list:
    file: lib/Gestinanna/Shell/Package.pm
  open:
    file: lib/Gestinanna/Shell/Package.pm
  set:
    file: lib/Gestinanna/Shell/Package.pm
  view:
    file: lib/Gestinanna/Shell/Package.pm
  write:
    file: lib/Gestinanna/Shell/Package.pm
generated_by: Module::Build version 0.21
